In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from matplotlib import pyplot as plt
import numpy as np

In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
# print(x_train.shape)
# print(y_train.shape)
# print(x_test.shape)
# print(y_test.shape)
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1) # Converting the 3D matrix into 4D for better results (we can implement Stochastic Gradient Descent)
x_test = x_test.reshape(x_test.shape[0],28,28,1)
# print(x_train.shape)
y_train = tf.keras.utils.to_categorical(y_train,10) #converts the data in a 2D matrix with the columns as class type(0-9) and rows as the number of training examples
y_test = tf.keras.utils.to_categorical(y_test,10)
# print(y_train.shape)

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train/255 #Converting the range of grayscale image pixel value from 0-255 to 0-1
x_test = x_test/255

In [6]:
model = keras.Sequential()
# model.add(layers.Conv2D(100,(3,3),activation= 'relu', input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(75,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(75, (3, 3), activation='relu'))
model.add(layers.Flatten())
# model.add(layers.Dense(75,activation='relu'))
model.add(layers.Dense(10,activation='sigmoid'))
opt = keras.optimizers.SGD(learning_rate=0.01)
# losses=tf.keras.losses.categorical_crossentropy()
model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])
hist = model.fit(x_train,y_train,batch_size=32,epochs=2,validation_data=(x_test,y_test))

Epoch 1/2
1875/1875 [==============================] - 31s 16ms/step - loss: 0.7518 - accuracy: 0.7912 - val_loss: 0.3116 - val_accuracy: 0.9078
Epoch 2/2
1875/1875 [==============================] - 32s 17ms/step - loss: 0.2669 - accuracy: 0.9205 - val_loss: 0.1968 - val_accuracy: 0.9414


In [ ]:
result = model.evaluate(x_test,y_test)
loss,acc=result
print(acc*100)

In [61]:
predictions = model.predict(x_test)
digit_predictions = tf.argmax(predictions, axis=1)
digits_true = tf.argmax(y_test,axis=1)
cf_matrix = tf.math.confusion_matrix(labels=digits_true,predictions=digit_predictions).numpy()
print(digit_predictions)
print(cf_matrix)
# cf_matrix=tf.math.confusion_matrix(labels=tf.)

313/313 [==============================] - 1s 3ms/step
tf.Tensor([7 2 1 ... 4 5 6], shape=(10000,), dtype=int64)
[[ 958    0    2    1    0    8    4    2    5    0]
 [   0 1101    6    4    2    2    4    1   15    0]
 [   9    0  943   21    6    3   11   13   19    7]
 [   5    0   19  945    0   11    1    8   17    4]
 [   0    2    6    1  900    0   24    2    6   41]
 [   5    2    6   31    3  813   10    2   19    1]
 [   7    4    4    3    5   24  907    0    4    0]
 [   4    7   27   15    3    3    0  904    3   62]
 [   4    4    6   34    8   23    5    4  870   16]
 [  10    5    7   20   31    5    0   11    4  916]]
